all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: "ubuntu"
          hostname: AnsibleMaster
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    prod:
      hosts:
        worker01: 
          ansible_host: 172.31.85.22
          hostname: AnsibleWorker01
          ansible_user: "ubuntu"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
